server:
  port: 8080
  servlet:
    context-path: /art-tracker-back
logging:
  level:
    org:
      springframework:
        web: DEBUG

spring:
  security:
    user:
      name: tek
      password: 123

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true


